# Generated by Django 4.1.7 on 2023-03-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='portfolio_rasmlar')),
                ('mavzu', models.CharField(max_length=200)),
                ('malumot', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_sharif', models.CharField(max_length=200)),
                ('yil', models.DateField()),
                ('manzil', models.CharField(max_length=200)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='rasmlar')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('telefon', models.CharField(max_length=13)),
                ('men_haqimda', models.TextField()),
                ('resume', models.FileField(upload_to='rezyumealrim')),
            ],
            options={
                'verbose_name': 'Men_haqimda',
                'verbose_name_plural': 'Men haqimda',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='portfolio_rasmlar')),
                ('nom', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1000)),
                ('malumot', models.TextField()),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
